# Creating an image canvas

install the pillow library (uncomment line below to install)

In [1]:
# pip install pillow

install the numpy library (uncomment line below to install)

In [12]:
# pip install numpy

In [2]:
# importing Modules from PIL
from PIL import Image, ImageDraw

checking root directory

In [3]:
pwd

'C:\\Users\\Ezekiel\\Documents\\BACUNGAN_GVC'

In [3]:
# canvas size
width, height = 20, 20

# Creata a new blank canvas (white background)
canvas = Image.new("RGB", (width, height), color="white")

# create a drawing context
draw = ImageDraw.Draw(canvas)

# draw a blue rectangle in the canvas
draw.rectangle([(2, 2), (15, 15)], fill="blue", outline="black");

# save the canvas as an image file (png)
canvas.save("blank_canvas_blue_rectangle.png")

# display the canvas
canvas.show()

In [4]:
# choose pixel to inspect (e.g., inse the blue rectangle)
x, y = 3, 3 # the coordinamtes should be within the size of the canvas
pixel_value = canvas.getpixel((x,y)) # getting the pixel value

# display the pixel value 
print(f"Pixel at ({x}, {y}: {pixel_value})") # should be blue (0, 0, 255)

Pixel at (3, 3: (0, 0, 255))


In [13]:
# importing numpy libraries as np
import numpy as np

# convert the canvas to numpy array
pixel_matrix = np.array(canvas)

# print the RGB matrix
for row in pixel_matrix:
    print(row)

[[255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]]
[[255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]]
[[255 255 255]
 [255 255 255]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]]
[[255 255 255]
 [255 255 255]
 [  0   0   0]
 [  0   0 255]
 [  0   0 255]
 [  0   0 255]
 [  0  